# Generated by Django 5.2.3 on 2025-06-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteluser',
            name='email_token',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
