# Generated by Django 5.2.3 on 2025-06-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_hoteluser_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelvendor',
            name='email_token',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
