# Generated by Django 5.2.3 on 2025-06-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_hotel_hotel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelvendor',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
